# DFT band plots

In [2]:
from post_procesing_tools import *
from post_procesing_tools_double import *

In [9]:


path1 ="/home/mjocic/data_paradox/nbnd_40"
path2 ="/home/mjocic/data_paradox/nbnd_80_sp"

path_plt = "/home/mjocic/Desktop/plot_tmp/poster/DFT"

E1_dft = Gather_E(path1,units='Electronvolt')
E2_dft = Gather_E(path2,units='Electronvolt')

k_mesh = Gather_K(path1)

k2=[0.0]
d=0
for i in range(len(k_mesh)-1):
    d1 = k_mesh[i+1]-k_mesh[i]
    d2 = np.sqrt(np.vdot(d1,d1))
    d += d2
    k2.append(d)
k2=np.array(k2)

x=[];y_dft1=[];y_dft2=[];

FILE_dft1 = open( path_plt+'/plotband_dft1.dat','w')
#FILE_dft2 = open( path_plt+'/plotband_dft2.dat','w')

for n in range(len(E1_dft[1])):
    for k_i in range(len(k_mesh)):
        x.append(k2[k_i])
        y_dft1.append(E1_dft[k_i][n]);
        #y_dft2.append(E2_dft[k_i][n])
        FILE_dft1.write("{} {} \n".format(k2[k_i],E1_dft[k_i][n]))
        #FILE_dft2.write("{} {} \n".format(k2[k_i],E2_dft[k_i][n]))
    FILE_dft1.write("\n")
    #FILE_dft2.write("\n")
FILE_dft1.close()
#FILE_dft2.close()

In [4]:
E1_dft[1]

array([-17.28701052, -17.28478122, -17.03640614, -17.03636562,
       -17.03636537, -15.46291799, -14.48770946, -14.47994951,
        -7.50628811,  -5.10384111,  -5.07027289,  -5.01435642,
        -2.60491543,  -2.59068281,  -2.57975095,  -2.49024636,
        -2.48643734,  -2.47610366,   2.45954563,   3.47879629,
         3.4848092 ,   4.32502524,   4.33179575,   4.33950313,
         5.93312754,   5.96659631,   6.03366577,   7.43609972,
         7.53705006,   7.56407877,   9.40519597,   9.51199186,
         9.52397592,  10.10272748,  10.30976294,  10.39813537,
        11.79689006,  11.85214654,  11.9315976 ,  12.40955687])

In [11]:
import matplotlib.pyplot as plt
%matplotlib
plt.plot(x,y_dft1,label='$w/o soc$')
#plt.plot(x,y_dft2, label='with soc')
plt.xlim(k2[0],k2[-1])
plt.ylim(-5.0,5.0)
#plt.xticks([k2[0],k2[10],k2[19]],('X','R','M'))
plt.xticks([k2[0],k2[10],k2[20],k2[30],k2[40]],('$\Gamma$','M','X','R','M'))
plt.ylabel('E(k) [eV]')
#plt.legend()
plt.show()

Using matplotlib backend: Qt5Agg


### Make a plot for 4x4 k.p Hamiltonian

In [92]:
from post_procesing_tools import *

path = "/home/mjocic/data_paradox/nbnd_120"
k_R=31
k_points= Gather_K(path)
k_Rpoint = k_points[k_R-1]

G_R = Gather_G(path,k_R)
C_R = Gather_C(path,k_R)
symmetry_list = Gather_Symmetries(path)

k_start=18
k_stop=20
matrices=Gather_Matrices(k_start,k_stop,symmetry_list,G_R,C_R,k_Rpoint)

path2="/home/mjocic/data_paradox"
G_25p = Gather_Symmetries(path2,"G25p_t2g.xml")

r = Compute_small_r(G_25p,matrices)
Unitary_transforms = Gather_Unitary_Transforms(r,G_25p,matrices)

u_11 = Unitary_transforms[0,0]
u_11i= nplin.inv(u_11)
u_11a = np.transpose(np.conjugate(u_11))

In [93]:
u_11a = np.transpose(np.conjugate(u_11))

In [94]:
basis_qe=C_R[18:21]
basis_g25p = u_11.T.dot(basis_qe)

In [95]:
basis4_g25p = np.array([C_R[17],basis_g25p[0],basis_g25p[1],basis_g25p[2]])
basis4_qe = C_R[17:21]
dim = len(basis4_g25p)
for m in range(dim):
    for n in range(dim):
        mat_qe = Compute_Matrix_Element(G_R,basis4_qe,m,n)
        mat_g25p = Compute_Matrix_Element(G_R,basis4_g25p,m,n)
        print("\n\tMatrix_element[{},{}]:\n - basis_qe: \n{} \n - basis_g_25:\n{}".format(m,n,mat_qe,mat_g25p))    


	Matrix_element[0,0]:
 - basis_qe: 
[-0.5+1.06706299e-22j -0.5+1.65436123e-24j -0.5+5.29395592e-23j] 
 - basis_g_25:
[-0.5+1.06706299e-22j -0.5+1.65436123e-24j -0.5+5.29395592e-23j]

	Matrix_element[0,1]:
 - basis_qe: 
[ 0.26634936-0.20792942j  0.06355563+0.04194552j -0.33515652+0.38637587j] 
 - basis_g_25:
[ 1.82769481e-10+2.83317409e-12j  1.93887799e-10+1.61457001e-10j
 -4.04775990e-01+4.66634738e-01j]

	Matrix_element[0,2]:
 - basis_qe: 
[ 0.44452084+0.03914511j -0.20938823-0.2775332j   0.24811558-0.00556916j] 
 - basis_g_25:
[-4.04775991e-01+4.66634739e-01j  2.53606410e-10+2.33358088e-10j
  1.67378745e-10+1.60664512e-10j]

	Matrix_element[0,3]:
 - basis_qe: 
[-0.03872225+0.25842683j -0.39787592+0.31083674j  0.04584511+0.23723667j] 
 - basis_g_25:
[ 7.62304975e-11-2.82586124e-10j -4.04775991e-01+4.66634739e-01j
 -3.55487963e-10-1.55858734e-10j]

	Matrix_element[1,0]:
 - basis_qe: 
[ 0.26634936+0.20792942j  0.06355563-0.04194552j -0.33515652-0.38637587j] 
 - basis_g_25:
[ 1.82769481

In [96]:
L = Compute_Matrix_Element(G_R,basis4_g25p,0,1)[2]
phi = np.arctan(L.imag/L.real)
phase = np.exp(1j*phi)
print('phase shift=',phase)
basis4_g25p = np.array([phase*C_R[17],basis_g25p[1],basis_g25p[2],basis_g25p[0]])
for m in range(1):
    for n in range(1,4):
        mat_g25p = Compute_Matrix_Element(G_R,basis4_g25p,m,n)
        print("\n\tMatrix_element[{},{}]:\n - basis_g_25:\n{}".format(m,n,mat_g25p))

phase shift= (0.6552625560079056-0.7554012064419716j)

	Matrix_element[0,1]:
 - basis_g_25:
[-6.17730995e-01-3.75982142e-11j -1.01002538e-11+3.44485288e-10j
 -1.16891104e-11+2.31715582e-10j]

	Matrix_element[0,2]:
 - basis_g_25:
[ 2.63416889e-10-1.27583550e-10j -6.17730995e-01-7.83384563e-11j
 -1.15202147e-10-3.70664402e-10j]

	Matrix_element[0,3]:
 - basis_g_25:
[ 1.17621748e-10+1.39920732e-10j  5.08262301e-12+2.52259702e-10j
 -6.17730994e-01-7.65601317e-18j]


In [97]:
path = "/home/mjocic/data_paradox/nbnd_120"

E = Gather_E(path,units='Hartree')
E_R = E[30]

#basis4_g25p = np.array([C_R[17],basis_g25p[1],basis_g25p[2],basis_g25p[0]])
basis4_qe= C_R[17:21]
Energy4 = np.array([E_R[17],E_R[18],E_R[19],E_R[20]])
k_mesh4 = k_points [20:41]

basis_ext = np.vstack((C_R[:17],C_R[21:]))
E_ext = np.append(E_R[:17],E_R[21:])

In [98]:
h0 , h0_eig = Compute_H0(k_mesh4,k_Rpoint,Energy4,a=10.8)
kdp1, kdp1_eig = Compute_KdP1(k_mesh4,k_Rpoint,G_R,basis4_g25p,a=10.8)
kdp2, kdp2_eig = Compute_KdP2(k_mesh4,k_Rpoint,Energy4,E_ext,G_R,basis4_g25p,basis_ext,a=10.8)

Calculating H0: DONE
Calculating KdP: DONE
Calculating KdP2: DONE


In [99]:
H_1 = h0 + kdp1 ;    eig_h1 = np.linalg.eigvalsh(H_1)
H_2 = h0+kdp1+kdp2 ; eig_h2 = np.linalg.eigvalsh(H_2)

In [118]:
print(k2[6],k2[-5])

0.4242640687119285 1.0071067811865477


In [111]:
path = '/home/mjocic/Desktop/plot_tmp/poster/k.p'
units = 1*2*13.605698066
Edft = E[20:40+1,17:21] * units
eig_0=h0_eig * units
eig_1=eig_h1 *units
eig_2=eig_h2 *units
k2=[0.0]
d=0

for i in range(len(k_mesh4)-1):
    d1 = k_mesh4[i+1]-k_mesh4[i]
    d2 = np.sqrt(np.vdot(d1,d1))
    d += d2
    k2.append(d)
k2=np.array(k2)
x=[];y_0=[];y_dft=[];y_1=[];y_2=[]
FILE_kp = open( path+'/kp_44.dat','w')

for n in range(eig_0.shape[1]):
    for k_i in range(len(k_mesh4)):
        x.append(k2[k_i])
        y_0.append(eig_0[k_i][n].real);
        y_1.append(eig_1[k_i][n].real)
        y_2.append(eig_2[k_i][n].real)
        y_dft.append(Edft[k_i][n])
        FILE_kp.write("{} {} {}\n".format (k2[k_i],eig_2[k_i][n].real,Edft[k_i][n]))
    FILE_kp.write("\n")
    #FILE_dft.write("\n")
FILE_kp.close()
#FILE_dft.close()

In [116]:
import matplotlib.pyplot as plt
%matplotlib
#plt.plot(x,y_0,label='$H_0$')
#plt.plot(x,y_1,label='$H_0+H_1$')
plt.plot(x,y_2,label='$H_0+H_1+H_2$')
plt.plot(x,y_dft, label='dft')
plt.xlim(k2[6],k2[-5])
#plt.ylim(y_dft[0],y_dft[1500])
plt.ylim(-2.0,2.6)
#plt.xticks([k2[0],k2[10],k2[19]],('X','R','M'))
plt.xticks([k2[10]],('R'))
plt.ylabel('E(k) [eV]')
plt.legend()
plt.show()
print('Points\nX = {}\nR = {}\nM={}\n'.format(k2[0],k2[10],k2[19]))

Using matplotlib backend: Qt5Agg
Points
X = 0.0
R = 0.7071067811865475
M=1.1571067811865479



In [6]:
char_g1 = np.array([1,1,1,1,1,1,1,1,1,1])
char_g2 = np.array([1,1,-1,-1,1,1,1,-1,-1,1])
char_g12= np.array([2,2,0,0,-1,2,2,0,0,-1])
char_g15= np.array([3,-1,1,-1,0,-3,1,-1,1,0])
char_g25= np.array([3,-1,-1,1,0,-3,1,1,-1,0])

char_g1p= np.array([1, 1, 1, 1, 1,-1,-1,-1,-1,-1])
char_g2p= np.array([1, 1,-1,-1, 1,-1,-1, 1, 1,-1])
char_g12p=np.array([2, 2, 0, 0,-1,-2,-2, 0, 0, 1])
char_g15p=np.array([3,-1, 1,-1, 0, 3,-1, 1,-1, 0])
char_g25p=np.array([3,-1,-1, 1, 0, 3,-1,-1, 1, 0])

Oh_sym = [[char_g1,"$\Gamma_1$"],[char_g2,"$\Gamma_2$"],
          [char_g12,"$\Gamma_{12}$"],
          [char_g15,"$\Gamma_{15}$"],
          [char_g25,"$\Gamma_{25}$"]]
Oh_symp = [[char_g1p,"$\Gamma^'_1$"],[char_g2p,"$\Gamma^'_2$"],
          [char_g12p,"$\Gamma^'_{12}$"],
          [char_g15p,"$\Gamma^'_{15}$"],
          [char_g25p,"$\Gamma^'_{25}$"]]

Nk = [1,3,6,6,8,1,3,6,6,8]

char_red = char_g2p*char_g15
for char_g in Oh_sym:
    c=char_coef(char_g[0],char_red,Nk)/48
    if (c)!=0:
          print(char_g[1],c)
for char_g in Oh_symp:
    c=char_coef(char_g[0],char_red,Nk)/48
    if (c)!=0:
          print(char_g[1],c)

$\Gamma^'_{25}$ 1.0


# Spin-orbit k.p

In [39]:
from post_procesing_tools_double import *
from test import *

path_so="/home/mjocic/data_paradox/nbnd_60_sp"
C_Rso = Gather_C_so(path_so,31,form='stack')
G_Rso = Gather_G_so(path_so,31)

k_index = 30
k_path = Gather_K(path=path_so)
k_Rpoint=k_path[k_index]

sym_path = "/home/mjocic/Post_processing/Symmetry_groups/Bilbao_server_pyreadable"
file_name="Oh_double.xml"
symmetries_double,sig_double=Gather_Symmetries_double(sym_path,file_name)

k_start=42
k_stop=43
basis_g7m = [C_Rso[0,k_start:k_stop+1],C_Rso[1,k_start:k_stop+1]]
g7m_full=Gather_Matrices_double(
    k_start,k_stop,symmetries_double,sig_double,
    G_Rso,C_Rso[0],C_Rso[1],k_Rpoint,details=True,all_elements=True)

k_start=44
k_stop=45
basis_g7p = [C_Rso[0,k_start:k_stop+1],C_Rso[1,k_start:k_stop+1]]
g7p_full=Gather_Matrices_double(
    k_start,k_stop,symmetries_double,sig_double,
    G_Rso,C_Rso[0],C_Rso[1],k_Rpoint,details=True,all_elements=True)

k_start=46
k_stop=49
basis_g8p = [C_Rso[0,k_start:k_stop+1],C_Rso[1,k_start:k_stop+1]]
g8p_full=Gather_Matrices_double(
    k_start,k_stop,symmetries_double,sig_double,
    G_Rso,C_Rso[0],C_Rso[1],k_Rpoint,details=True,all_elements=True)

Dimension of 3x3x3 square matrix is: 33
Creating G-matrix
G-matrix: Done

Now performing for identity

Symm.Op. matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Spin.Op. matrix:
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
Matrix = 
 [[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]

Now performing for 180 deg rotation - cart. axis [0,0,1]

Symm.Op. matrix:
[[-1  0  0]
 [ 0 -1  0]
 [ 0  0  1]]
Spin.Op. matrix:
[[-0.-1.j  0.+0.j]
 [ 0.+0.j  0.+1.j]]
Matrix = 
 [[ 0.        +0.32986275j -0.88304647-0.3337956j ]
 [ 0.88304647-0.3337956j   0.        -0.32986275j]]

Now performing for 180 deg rotation - cart. axis [0,1,0]

Symm.Op. matrix:
[[-1  0  0]
 [ 0  1  0]
 [ 0  0 -1]]
Spin.Op. matrix:
[[ 0.+0.j -1.+0.j]
 [ 1.+0.j  0.+0.j]]
Matrix = 
 [[ 0.        -0.9377006j  -0.34735846-0.00772579j]
 [ 0.34735846-0.00772579j  0.        +0.9377006j ]]

Now performing for 180 deg rotation - cart. axis [1,0,0]

Symm.Op. matrix:
[[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
Spin.Op. matrix:
[[ 0.+0.j -0.-1.j]
 [-0.-1.j  0.+0.j]]
Matrix = 
 [[ 0.   

Matrix = 
 [[ 0.        -0.1091245j   0.31554878-0.94261382j]
 [-0.31554878-0.94261382j  0.        +0.1091245j ]]

Now performing for inv. 120 deg rotation - cart. axis [1,1,1]

Symm.Op. matrix:
[[ 0  0 -1]
 [-1  0  0]
 [ 0 -1  0]]
Spin.Op. matrix:
[[ 0.5-0.5j -0.5-0.5j]
 [ 0.5-0.5j  0.5+0.5j]]
Matrix = 
 [[-0.5       +0.24935667j  0.77297686-0.30054621j]
 [-0.77297686-0.30054621j -0.5       -0.24935667j]]

Now performing for inv. 120 deg rotation - cart. axis [-1,1,-1]

Symm.Op. matrix:
[[ 0  0 -1]
 [ 1  0  0]
 [ 0  1  0]]
Spin.Op. matrix:
[[ 0.5+0.5j -0.5+0.5j]
 [ 0.5+0.5j  0.5-0.5j]]
Matrix = 
 [[-0.5       +0.68834392j -0.42561839+0.308272j  ]
 [ 0.42561839+0.308272j   -0.5       -0.68834392j]]

Now performing for inv. 120 deg rotation - cart. axis [1,-1,-1]

Symm.Op. matrix:
[[ 0  0  1]
 [ 1  0  0]
 [ 0 -1  0]]
Spin.Op. matrix:
[[ 0.5+0.5j  0.5-0.5j]
 [-0.5-0.5j  0.5-0.5j]]
Matrix = 
 [[-0.5       -0.35848117j -0.45742807-0.6420676j ]
 [ 0.45742807-0.6420676j  -0.5       +0.358481

Matrix = 
 [[-0.5       -0.35848117j -0.45742807-0.6420676j ]
 [ 0.45742807-0.6420676j  -0.5       +0.35848117j]]

Now performing for 120 deg rotation - cart. axis [-1,-1,1]+d

Symm.Op. matrix:
[[ 0  0 -1]
 [ 1  0  0]
 [ 0 -1  0]]
Spin.Op. matrix:
[[-0.5+0.5j -0.5-0.5j]
 [ 0.5-0.5j -0.5-0.5j]]
Matrix = 
 [[-0.5       -0.57921942j  0.11006961+0.63434182j]
 [-0.11006961+0.63434182j -0.5       +0.57921942j]]

Now performing for 120 deg rotation - cart. axis [-1,-1,-1]+d

Symm.Op. matrix:
[[0 1 0]
 [0 0 1]
 [1 0 0]]
Spin.Op. matrix:
[[-0.5-0.5j -0.5-0.5j]
 [ 0.5-0.5j -0.5+0.5j]]
Matrix = 
 [[-0.5       -0.24935667j -0.77297686+0.30054621j]
 [ 0.77297686+0.30054621j -0.5       +0.24935667j]]

Now performing for 120 deg rotation - cart. axis [-1,1,1]+d

Symm.Op. matrix:
[[ 0 -1  0]
 [ 0  0  1]
 [-1  0  0]]
Spin.Op. matrix:
[[-0.5+0.5j  0.5-0.5j]
 [-0.5-0.5j -0.5-0.5j]]
Matrix = 
 [[-0.5       +0.35848117j  0.45742807+0.6420676j ]
 [-0.45742807+0.6420676j  -0.5       -0.35848117j]]

Now perfo

Matrix = 
 [[ 0.5       -0.35848117j -0.45742807-0.6420676j ]
 [ 0.45742807-0.6420676j   0.5       +0.35848117j]]

Now performing for inv. 120 deg rotation - cart. axis [1,1,-1]+d

Symm.Op. matrix:
[[ 0 -1  0]
 [ 0  0  1]
 [ 1  0  0]]
Spin.Op. matrix:
[[-0.5-0.5j  0.5+0.5j]
 [-0.5+0.5j -0.5+0.5j]]
Matrix = 
 [[ 0.5       -0.57921942j  0.11006961+0.63434182j]
 [-0.11006961+0.63434182j  0.5       +0.57921942j]]

Now performing for inv. 120 deg rotation - cart. axis [1,-1,1]+d

Symm.Op. matrix:
[[ 0  1  0]
 [ 0  0  1]
 [-1  0  0]]
Spin.Op. matrix:
[[-0.5+0.5j -0.5+0.5j]
 [ 0.5+0.5j -0.5-0.5j]]
Matrix = 
 [[ 0.5       +0.68834392j -0.42561839+0.308272j  ]
 [ 0.42561839+0.308272j    0.5       -0.68834392j]]

Now performing for inv. 180 deg rotation - cart. axis [1,1,0]+d

Symm.Op. matrix:
[[ 0 -1  0]
 [-1  0  0]
 [ 0  0  1]]
Spin.Op. matrix:
[[-0.        -0.j          0.70710678+0.70710678j]
 [-0.70710678+0.70710678j -0.        -0.j        ]]
Matrix = 
 [[ 0.        +0.58589178j  0.46874621

Matrix = 
 [[ 0.        +0.79644965j -0.35509772-0.48946252j]
 [ 0.35509772-0.48946252j  0.        -0.79644965j]]

Now performing for 180 deg rotation - cart. axis [1,-1,0]

Symm.Op. matrix:
[[ 0 -1  0]
 [-1  0  0]
 [ 0  0 -1]]
Spin.Op. matrix:
[[ 0.        +0.j         -0.70710678+0.70710678j]
 [ 0.70710678+0.70710678j  0.        +0.j        ]]
Matrix = 
 [[ 0.        -0.52538113j -0.80710896-0.26935069j]
 [ 0.80710896-0.26935069j  0.        +0.52538113j]]

Now performing for  90 deg rotation - cart. axis [0,0,-1]

Symm.Op. matrix:
[[ 0  1  0]
 [-1  0  0]
 [ 0  0  1]]
Spin.Op. matrix:
[[0.70710678+0.70710678j 0.        +0.j        ]
 [0.        +0.j         0.70710678-0.70710678j]]
Matrix = 
 [[-0.70710678-0.21171043j  0.33352716-0.58646255j]
 [-0.33352716-0.58646255j -0.70710678+0.21171043j]]

Now performing for  90 deg rotation - cart. axis [0,0,1]

Symm.Op. matrix:
[[ 0 -1  0]
 [ 1  0  0]
 [ 0  0  1]]
Spin.Op. matrix:
[[0.70710678-0.70710678j 0.        +0.j        ]
 [0.        +0.

Matrix = 
 [[-0.70710678+0.21171043j -0.33352716+0.58646255j]
 [ 0.33352716+0.58646255j -0.70710678-0.21171043j]]

Now performing for inv.  90 deg rotation - cart. axis [-1,0,0]

Symm.Op. matrix:
[[-1  0  0]
 [ 0  0 -1]
 [ 0  1  0]]
Spin.Op. matrix:
[[0.70710678+0.j         0.        +0.70710678j]
 [0.        +0.70710678j 0.70710678+0.j        ]]
Matrix = 
 [[-0.70710678-0.66091539j -0.22600562+0.11005591j]
 [ 0.22600562+0.11005591j -0.70710678+0.66091539j]]

Now performing for inv. 180 deg rotation - cart. axis [0,1,1]

Symm.Op. matrix:
[[ 1  0  0]
 [ 0  0 -1]
 [ 0 -1  0]]
Spin.Op. matrix:
[[ 0.        +0.70710678j  0.70710678+0.j        ]
 [-0.70710678+0.j          0.        -0.70710678j]]
Matrix = 
 [[ 0.       -0.34724469j  0.9146305-0.20705595j]
 [-0.9146305-0.20705595j  0.       +0.34724469j]]

Now performing for inv. 180 deg rotation - cart. axis [0,1,-1]

Symm.Op. matrix:
[[1 0 0]
 [0 0 1]
 [0 1 0]]
Spin.Op. matrix:
[[ 0.        -0.70710678j  0.70710678+0.j        ]
 [-0.707106

Matrix = 
 [[ 0.        -0.07617617j -0.24757618-0.96586916j]
 [ 0.24757618-0.96586916j  0.        +0.07617617j]]

Now performing for  90 deg rotation - cart. axis [1,0,0]+d

Symm.Op. matrix:
[[ 1  0  0]
 [ 0  0 -1]
 [ 0  1  0]]
Spin.Op. matrix:
[[-0.70710678-0.j         -0.        +0.70710678j]
 [-0.        +0.70710678j -0.70710678-0.j        ]]
Matrix = 
 [[ 0.70710678-0.66091539j -0.22600562+0.11005591j]
 [ 0.22600562+0.11005591j  0.70710678+0.66091539j]]

Now performing for  90 deg rotation - cart. axis [0,1,0]+d

Symm.Op. matrix:
[[ 0  0  1]
 [ 0  1  0]
 [-1  0  0]]
Spin.Op. matrix:
[[-0.70710678-0.j  0.70710678-0.j]
 [-0.70710678-0.j -0.70710678-0.j]]
Matrix = 
 [[ 0.70710678-0.13553426j  0.58110334+0.3794066j ]
 [-0.58110334+0.3794066j   0.70710678+0.13553426j]]

Now performing for 180 deg rotation - cart. axis [1,0,1]+d

Symm.Op. matrix:
[[ 0  0  1]
 [ 0 -1  0]
 [ 1  0  0]]
Spin.Op. matrix:
[[-0.+0.70710678j -0.+0.70710678j]
 [-0.+0.70710678j -0.-0.70710678j]]
Matrix = 
 [[ 0. 

Matrix = 
 [[ 0.70710678-0.13553426j  0.58110334+0.3794066j ]
 [-0.58110334+0.3794066j   0.70710678+0.13553426j]]

Now performing for inv. 180 deg rotation - cart. axis [1,0,1]+d

Symm.Op. matrix:
[[ 0  0 -1]
 [ 0  1  0]
 [-1  0  0]]
Spin.Op. matrix:
[[-0.+0.70710678j -0.+0.70710678j]
 [-0.+0.70710678j -0.-0.70710678j]]
Matrix = 
 [[ 0.        -0.87262583j  0.10752154-0.47640664j]
 [-0.10752154-0.47640664j  0.        +0.87262583j]]

Now performing for inv.  90 deg rotation - cart. axis [0,-1,0]+d

Symm.Op. matrix:
[[ 0  0  1]
 [ 0 -1  0]
 [-1  0  0]]
Spin.Op. matrix:
[[-0.70710678-0.j -0.70710678-0.j]
 [ 0.70710678-0.j -0.70710678-0.j]]
Matrix = 
 [[ 0.70710678+0.13553426j -0.58110334-0.3794066j ]
 [ 0.58110334-0.3794066j   0.70710678-0.13553426j]]

Now performing for inv. 180 deg rotation - cart. axis [-1,0,1]+d

Symm.Op. matrix:
[[0 0 1]
 [0 1 0]
 [1 0 0]]
Spin.Op. matrix:
[[-0.-0.70710678j -0.+0.70710678j]
 [-0.+0.70710678j -0.+0.70710678j]]
Matrix = 
 [[ 0.        -0.44920496j -0.5

Matrix = 
 [[ 0.        +0.01672848j  0.45448834+0.23442218j -0.43092814+0.49753104j
   0.4681815 +0.29287648j]
 [-0.45448834+0.23442218j  0.        -0.70735181j -0.46306516-0.01146233j
  -0.1244813 +0.08990932j]
 [ 0.43092814+0.49753104j  0.46306516-0.01146233j  0.        +0.11418199j
  -0.58237862-0.00083248j]
 [-0.4681815 +0.29287648j  0.1244813 +0.08990932j  0.58237862-0.00083248j
   0.        +0.57644134j]]

Now performing for 180 deg rotation - cart. axis [1,-1,0]

Symm.Op. matrix:
[[ 0 -1  0]
 [-1  0  0]
 [ 0  0 -1]]
Spin.Op. matrix:
[[ 0.        +0.j         -0.70710678+0.70710678j]
 [ 0.70710678+0.70710678j  0.        +0.j        ]]
Matrix = 
 [[ 0.        -0.8992097j  -0.29076547+0.018864j   -0.28815504+0.04533771j
   0.07146704-0.12776987j]
 [ 0.29076547+0.018864j    0.        +0.09714436j -0.21399094+0.56731162j
  -0.71451095+0.16583749j]
 [ 0.28815504+0.04533771j  0.21399094+0.56731162j  0.        +0.46757165j
   0.50300145-0.27503249j]
 [-0.07146704-0.12776987j  0.7145109

Matrix = 
 [[ 0.        +0.35292419j -0.69511587-0.4669257j  -0.14780768+0.3144875j
   0.18278929+0.14169481j]
 [ 0.69511587-0.4669257j   0.        -0.29614803j -0.15396843-0.22477521j
   0.36612166+0.05306055j]
 [ 0.14780768+0.3144875j   0.15396843-0.22477521j  0.        +0.01238456j
   0.07579068-0.89393665j]
 [-0.18278929+0.14169481j -0.36612166+0.05306055j -0.07579068-0.89393665j
   0.        -0.06916071j]]

Now performing for inv. 180 deg rotation - cart. axis [1,0,0]

Symm.Op. matrix:
[[-1  0  0]
 [ 0  1  0]
 [ 0  0  1]]
Spin.Op. matrix:
[[ 0.+0.j -0.-1.j]
 [-0.-1.j  0.+0.j]]
Matrix = 
 [[ 0.        +0.20805433j -0.12910299+0.14116925j -0.45445716-0.41996844j
   0.33024257-0.65433332j]
 [ 0.12910299+0.14116925j  0.        +0.59604764j -0.46094537-0.14610043j
   0.04508529+0.61014935j]
 [ 0.45445716-0.41996844j  0.46094537-0.14610043j  0.        -0.58536504j
  -0.20072005+0.0183973j ]
 [-0.33024257-0.65433332j -0.04508529+0.61014935j  0.20072005+0.0183973j
   0.        -0.21873693

Matrix = 
 [[ 0.08107149+0.11994119j -0.4779389 +0.765415j    0.38355443+0.07263205j
   0.00519407+0.11108292j]
 [-0.36422452+0.31331142j -0.18694617-0.04999403j -0.11602129-0.43023136j
   0.72093168+0.11586943j]
 [ 0.38717437+0.57367026j  0.26670453-0.16536894j  0.20736644+0.42712805j
   0.23135967+0.37888488j]
 [-0.43733606+0.27920172j  0.16335078-0.15200112j  0.64955273+0.04114194j
  -0.10149176-0.49707521j]]

Now performing for inv. 180 deg rotation - cart. axis [0,1,1]

Symm.Op. matrix:
[[ 1  0  0]
 [ 0  0 -1]
 [ 0 -1  0]]
Spin.Op. matrix:
[[ 0.        +0.70710678j  0.70710678+0.j        ]
 [-0.70710678+0.j          0.        -0.70710678j]]
Matrix = 
 [[ 0.        -0.0069256j   0.09954569-0.05704524j  0.19794655-0.59023951j
   0.58770241+0.50381435j]
 [-0.09954569-0.05704524j  0.        -0.72910742j -0.4728286 +0.15709073j
  -0.12855105+0.43642768j]
 [-0.19794655-0.59023951j  0.4728286 +0.15709073j  0.        +0.48377736j
   0.35385937+0.07023614j]
 [-0.58770241+0.50381435j  0.128

Matrix = 
 [[ 0.0746892 -0.24279143j  0.66646739+0.46878656j  0.07972194-0.41571863j
  -0.26653074-0.14600691j]
 [-0.15124854-0.17410939j -0.20331534+0.51776783j -0.60567585+0.12164713j
  -0.12134526+0.49094114j]
 [-0.64918573+0.34040651j -0.066383  +0.08545445j  0.46480629-0.18056205j
  -0.27991893+0.35209372j]
 [-0.43303277-0.39679663j -0.12212153+0.00410849j -0.03027455-0.43545044j
   0.66381986-0.09441435j]]

Now performing for 120 deg rotation - cart. axis [-1,-1,1]+d

Symm.Op. matrix:
[[ 0  0 -1]
 [ 1  0  0]
 [ 0 -1  0]]
Spin.Op. matrix:
[[-0.5+0.5j -0.5-0.5j]
 [ 0.5-0.5j -0.5-0.5j]]
Matrix = 
 [[-0.12996333-0.28691179j  0.11596236-0.11342253j  0.4344788 +0.3217622j
  -0.40926015+0.64395855j]
 [-0.71924926+0.45511946j  0.25367841+0.07059757j -0.02016591+0.42621145j
   0.0384188 -0.15056943j]
 [-0.13030395-0.25182617j -0.55614398-0.2373022j   0.49137617+0.26307951j
   0.09205356-0.48462436j]
 [ 0.29384149-0.09797741j  0.23410027+0.69565789j  0.34389328+0.31098303j
   0.38490874-0.

Matrix = 
 [[-0.08107149+0.11994119j  0.36422452+0.31331142j -0.38717437+0.57367026j
   0.43733606+0.27920172j]
 [ 0.4779389 +0.765415j    0.18694617-0.04999403j -0.26670453-0.16536894j
  -0.16335078-0.15200112j]
 [-0.38355443+0.07263205j  0.11602129-0.43023136j -0.20736644+0.42712805j
  -0.64955273+0.04114194j]
 [-0.00519407+0.11108292j -0.72093168+0.11586943j -0.23135967+0.37888488j
   0.10149176-0.49707521j]]

Now performing for  90 deg rotation - cart. axis [0,1,0]+d

Symm.Op. matrix:
[[ 0  0  1]
 [ 0  1  0]
 [-1  0  0]]
Spin.Op. matrix:
[[-0.70710678-0.j  0.70710678-0.j]
 [-0.70710678-0.j -0.70710678-0.j]]
Matrix = 
 [[ 0.008835  +0.0100302j   0.02399907-0.05550931j -0.13079356+0.53514845j
  -0.60502174-0.57150851j]
 [-0.33408918+0.27072925j -0.36977592+0.04110457j -0.05956846-0.67959462j
  -0.40906513-0.20960617j]
 [ 0.49229743+0.58699455j  0.11754175+0.31253169j  0.45942148-0.06625538j
   0.09672282-0.27708363j]
 [-0.44087559+0.18335969j  0.86351864+0.02761119j  0.01030745-0.124

Matrix = 
 [[ 0.0746892 +0.24279143j -0.15124854+0.17410939j -0.64918573-0.34040651j
  -0.43303277+0.39679663j]
 [ 0.66646739-0.46878656j -0.20331534-0.51776783j -0.066383  -0.08545445j
  -0.12212153-0.00410849j]
 [ 0.07972194+0.41571863j -0.60567585-0.12164713j  0.46480629+0.18056205j
  -0.03027455+0.43545044j]
 [-0.26653074+0.14600691j -0.12134526-0.49094114j -0.27991893-0.35209372j
   0.66381986+0.09441435j]]

Now performing for inv. 120 deg rotation - cart. axis [1,1,-1]+d

Symm.Op. matrix:
[[ 0 -1  0]
 [ 0  0  1]
 [ 1  0  0]]
Spin.Op. matrix:
[[-0.5-0.5j  0.5+0.5j]
 [-0.5+0.5j -0.5+0.5j]]
Matrix = 
 [[-0.12996333+0.28691179j -0.71924926-0.45511946j -0.13030395+0.25182617j
   0.29384149+0.09797741j]
 [ 0.11596236+0.11342253j  0.25367841-0.07059757j -0.55614398+0.2373022j
   0.23410027-0.69565789j]
 [ 0.4344788 -0.3217622j  -0.02016591-0.42621145j  0.49137617-0.26307951j
   0.34389328-0.31098303j]
 [-0.40926015-0.64395855j  0.0384188 +0.15056943j  0.09205356+0.48462436j
   0.3849087

Matrix = 
 [[ 0.008835  -0.0100302j  -0.33408918-0.27072925j  0.49229743-0.58699455j
  -0.44087559-0.18335969j]
 [ 0.02399907+0.05550931j -0.36977592-0.04110457j  0.11754175-0.31253169j
   0.86351864-0.02761119j]
 [-0.13079356-0.53514845j -0.05956846+0.67959462j  0.45942148+0.06625538j
   0.01030745+0.1246909j ]
 [-0.60502174+0.57150851j -0.40906513+0.20960617j  0.09672282+0.27708363j
  -0.09848056-0.0151206j ]]

Now performing for inv. 180 deg rotation - cart. axis [-1,0,1]+d

Symm.Op. matrix:
[[0 0 1]
 [0 1 0]
 [1 0 0]]
Spin.Op. matrix:
[[-0.-0.70710678j -0.+0.70710678j]
 [-0.+0.70710678j -0.+0.70710678j]]
Matrix = 
 [[ 0.        +0.88081321j  0.42440946-0.06334691j  0.18335646-0.03547024j
  -0.06417065+0.03219106j]
 [-0.42440946-0.06334691j  0.        -0.84721282j -0.03408345+0.03762096j
   0.003676  +0.3090367j ]
 [-0.18335646-0.03547024j  0.03408345+0.03762096j  0.        -0.95751227j
   0.20967145-0.04187337j]
 [ 0.06417065+0.03219106j -0.003676  +0.3090367j  -0.20967145-0.041873

In [41]:
from test import *

path = "/home/mjocic/Post_processing/Symmetry_groups/Bilbao_server_pyreadable"

file = "GM7m_E2u_GM9.xml"
#file = "GM7m_new.xml"
GM7m = Gather_irrep2(path,file)
file_d = "GM7m_E2u_GM9+d.xml"
#file_d = "GM7m+d_new.xml"
GM7m_d = Gather_irrep2(path,file_d)
GM7m.extend(GM7m_d)

file = "GM7p_E2g_GM7.xml"
#file = "GM7p_new2.xml"
GM7p = Gather_irrep2(path,file)
file_d = "GM7p_E2g_GM7+d.xml"
#file_d = "GM7p+d_new2.xml"
GM7p_d = Gather_irrep2(path,file_d)
GM7p.extend(GM7p_d)

file = "GM8p_Fg_GM10.xml"
GM8p = Gather_irrep4(path,file)
file_d = "GM8p_Fg_GM10+d.xml"
GM8p_d = Gather_irrep4(path,file_d)
GM8p.extend(GM8p_d)

In [42]:
r_g7m = Compute_small_r(GM7m, g7m_full)
r_g7p = Compute_small_r(GM7p, g7p_full)
r_g8p = Compute_small_r(GM8p, g8p_full)

U_g7m = Gather_Unitary_Transforms(r_g7m, GM7m, g7m_full)[0,0]
U_g7p = Gather_Unitary_Transforms(r_g7p, GM7p, g7p_full)[0,0]
U_g8p = Gather_Unitary_Transforms(r_g8p, GM8p, g8p_full)[0,0]

In [43]:
k_start=42
k_stop=43
basis_g7m = np.array([C_Rso[0,k_start:k_stop+1],C_Rso[1,k_start:k_stop+1]])
k_start=44
k_stop=45
basis_g7p = np.array([C_Rso[0,k_start:k_stop+1],C_Rso[1,k_start:k_stop+1]])
k_start=46
k_stop=49
basis_g8p = np.array([C_Rso[0,k_start:k_stop+1],C_Rso[1,k_start:k_stop+1]])

In [44]:
psi_up,psi_dn = U_g7m.T.dot(basis_g7m[0]), U_g7m.T.dot(basis_g7m[1])
newbasis_g7m = np.array([psi_up,psi_dn])

psi_up,psi_dn = U_g7p.T.dot(basis_g7p[0]), U_g7p.T.dot(basis_g7p[1])
newbasis_g7p = np.array([psi_up,psi_dn])

psi_up,psi_dn = U_g8p.T.dot(basis_g8p[0]), U_g8p.T.dot(basis_g8p[1])
newbasis_g8p = np.array([psi_up,psi_dn])

In [45]:
spin_up=np.concatenate((newbasis_g7m[0],newbasis_g7p[0],newbasis_g8p[0]),axis=0)
spin_dn=np.concatenate((newbasis_g7m[1],newbasis_g7p[1],newbasis_g8p[1]),axis=0)
basis8 = np.array([spin_up,spin_dn])
print(basis8.shape)

(2, 8, 16560)


In [46]:
#for m in range(len(basis8[0])):
m=0
for n in range(len(basis8[0])):
    up = Compute_Matrix_Element(G_Rso,basis8[0],m,n)
    dn = Compute_Matrix_Element(G_Rso,basis8[1],m,n)
    print("KdP_so[{},{}] =\n{}\n".format(m,n,up+dn))

KdP_so[0,0] =
[-0.49999994+3.73523745e-24j -0.49999987+1.65436123e-24j
 -0.50000002-1.08416753e-19j]

KdP_so[0,1] =
[-1.51290926e-07+3.10543946e-08j -2.43893905e-07-7.28143244e-08j
 -1.74847459e-07-1.12018011e-08j]

KdP_so[0,2] =
[-1.60148694e-07-2.26474107e-07j -1.00015943e-07+5.78244231e-08j
 -3.80866921e-01+1.26040675e-01j]

KdP_so[0,3] =
[-3.80866994e-01+1.26040778e-01j  1.26040783e-01+3.80867099e-01j
 -1.57331826e-08-1.29702016e-07j]

KdP_so[0,4] =
[ 2.57359897e-09+2.12950377e-07j -1.61615038e-07+3.10031833e-07j
 -2.55986978e-01-1.93827088e-01j]

KdP_so[0,5] =
[-3.98657116e-02+3.18604912e-01j -1.24777858e-01-2.95852639e-01j
  1.56523287e-07-6.18210393e-08j]

KdP_so[0,6] =
[-1.20968356e-01+2.97430945e-01j -2.53477188e-01+1.97098464e-01j
  4.71908022e-09+7.81844671e-08j]

KdP_so[0,7] =
[ 1.68299933e-07-2.34527936e-07j  3.03331011e-07+6.36473471e-09j
 -4.39539103e-02-3.18066747e-01j]



In [47]:
A = -3.80866921e-01+1.26040675e-01j
B = -2.55986978e-01-1.93827088e-01j
G = -4.39539103e-02-3.18066747e-01j
phi_a = np.arctan(A.imag/A.real)
B = B*np.exp(-1j*phi_a)
phi_b = -np.arctan(B.imag/B.real)
G = G*np.exp(-1j*phi_a)
phi_g = -np.arctan(G.imag/G.real)

basis8[:,0:2] = np.exp(1j*phi_a)*basis8[:,0:2]
basis8[:,4:6] = np.exp(1j*phi_b)*basis8[:,4:6]
basis8[:,6:8] = np.exp(1j*phi_g)*basis8[:,6:8]
#z_a = A.real*(np.cos(phi) + np.sin(phi)**2/np.cos(phi))
#print(abs(A),abs(z_a))
#B = [1,2,3,4,5,6]
#B = np.array(B)
#print(B*np.exp(1j*phi))

In [48]:
#Check parameters now:

#for m in range(len(basis8[0])):
m=0
for n in range(len(basis8[0])):
    up = Compute_Matrix_Element(G_Rso,basis8[0],m,n)
    dn = Compute_Matrix_Element(G_Rso,basis8[1],m,n)
    print("KdP_so[{},{}] =\n{}\n".format(m,n,up+dn))

KdP_so[0,0] =
[-0.49999994+3.38848205e-20j -0.49999987+6.76964613e-21j
 -0.50000002+6.13923111e-25j]

KdP_so[0,1] =
[-1.51290926e-07+3.10543946e-08j -2.43893905e-07-7.28143244e-08j
 -1.74847459e-07-1.12018010e-08j]

KdP_so[0,2] =
[-8.08872411e-08-2.65321276e-07j -1.13118618e-07+2.34740496e-08j
 -4.01180587e-01-1.07475053e-10j]

KdP_so[0,3] =
[-4.01180689e-01+7.49440627e-08j  4.70135040e-08+4.01180790e-01j
  2.58125170e-08-1.28077554e-07j]

KdP_so[0,4] =
[ 1.30600343e-07+1.68220204e-07j  5.83053632e-08+3.44731262e-07j
 -3.21089198e-01+4.66356623e-10j]

KdP_so[0,5] =
[ 1.60544670e-01+2.78071527e-01j -2.78071523e-01-1.60544467e-01j
  8.74689385e-08-1.43772616e-07j]

KdP_so[0,6] =
[-2.78071657e-01-1.60544898e-01j -1.60544552e-01-2.78071818e-01j
 -7.80944536e-08-6.02801148e-09j]

KdP_so[0,7] =
[ 2.09281583e-07+1.98820118e-07j -4.78277843e-08+2.99604264e-07j
  3.21089398e-01-3.38684742e-11j]



In [49]:
basis8_qe = np.array([C_Rso[0,42:50],C_Rso[1,42:50]])

path_so_more="/home/mjocic/data_paradox/nbnd_240_sp"
C_Rso = Gather_C_so(path_so_more,31,form='stack')
G_Rso = Gather_G_so(path_so_more,31)

basis_ext_up = np.vstack((C_Rso[0,:42],C_Rso[0,50:]))
basis_ext_dn = np.vstack((C_Rso[1,:42],C_Rso[1,50:]))


E_Rso = Gather_E(path_so_more,units='Hartree')[k_index]
Energy8 = E_Rso[42:50]
E_ext = np.append(E_Rso[:42],E_Rso[50:])

In [50]:
k_mesh = k_path[20:40]

h0 , h0_eig = Compute_H0(k_mesh,k_Rpoint,Energy8,a=10.8)
kdp1, kdp1_eig = Compute_KdP1_spin(k_mesh,k_Rpoint,
                                   G_Rso,basis8[0],basis8[1],a=10.8)
kdp2, kdp2_eig = Compute_KdP2_spin(k_mesh,k_Rpoint,Energy8,E_ext,
                                   G_Rso,basis8[0],basis8[1],
                                   basis_ext_up,basis_ext_dn,a=10.8)

Calculating H0: DONE
Calculating KdP1: DONE

Calculating KdP2: DONE



In [82]:
H_1so = h0 + kdp1 ;        eig_h1so = np.linalg.eigvalsh(H_1)
H_2so = H_1 + kdp2 ;       eig_h2so = np.linalg.eigvalsh(H_2)

In [83]:
k2=[0.0]
d=0
k_mesh4=k_mesh
for i in range(len(k_mesh4)-1):
    d1 = k_mesh4[i+1]-k_mesh4[i]
    d2 = np.sqrt(np.vdot(d1,d1))
    d += d2
    k2.append(d)
k2=np.array(k2)

#path = '/home/mjocic/Desktop/plot_tmp'
units = 1*2*13.605698066
Edft = Gather_E(path_so,units='Electronvolt')[20:40,42:50]

#eig_0=eig_h3 * units
eig_1=eig_h2so *units
#eig_2=eig_h2_qe *units
x=[];y_0=[];y_dft=[];y_1=[];y_2=[]
path = '/home/mjocic/Desktop/plot_tmp/poster/k.p'
FILE_kp = open( path+'/kp_88.dat','w')

for n in range(eig_1.shape[1]):
    for k_i in range(len(k_mesh4)):
        x.append(k2[k_i])
        #y_0.append(eig_0[k_i][n].real);
        y_1.append(eig_1[k_i][n].real)
        #y_2.append(eig_2[k_i][n].real)
        y_dft.append(Edft[k_i][n])
        FILE_kp.write("{} {} {}\n".format (k2[k_i],eig_1[k_i][n].real,Edft[k_i][n]))
    FILE_kp.write("\n")
    #FILE_dft.write("\n")
FILE_kp.close()
#FILE_dft.close()

In [85]:
import matplotlib.pyplot as plt
%matplotlib
#plt.plot(x,y_0,label='$H_2+relkin$')
plt.plot(x,y_1,'x',label='$H_2$')
#plt.plot(x,y_2,'+',label='$H_2$')
plt.plot(x,y_dft,'p' ,label='dft')
plt.xlim(k2[6],k2[-5])
#plt.ylim(y_dft[0],y_dft[1500])
plt.ylim(-2,6)
#plt.xticks([k2[0],k2[10],k2[19]],('X','R','M'))
plt.xticks([k2[10]],('R'))
plt.ylabel('E(k) [Electronvolt]')
#plt.legend()
plt.show()

Using matplotlib backend: Qt5Agg
